name: Deploy to Zone
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ruudus.eu
    steps:
      - name: Checkout to main
        uses: actions/checkout@main
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Copy files to server
        run: |
          rsync -vrm -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            ./* ${{ secrets.SSH_LOGIN_CREDS }}:/data01/virt145949/domeenid/www.ruudus.eu/htdocs
